Topics:
  gps_topic: '/gnss'
  lidar_topic: '/rslidar_points'

Extractor:
  # Mention file format to save lidar frames (for now do not set pcd)
  save_as: 'ply'

Preprocessor:
  # Specify drive distance threshold in meters, if drive distance crosses
  # this threshold it will auto trigger advanced preprocessing if set False
  drive_distance_thresh: 230
  basic_preprocessing: True
  advanced_preprocessing: False
  # Basic preprocessing parameters
  road_value_z: -2.9
  # Advanced preprocessing parameters
  k_nbs: 10
  z_thresh: 3
  z_filter: [-2.9, 3]

LidarOdometry:
  max_range: 100
  deskew: True

TrajectoryTransformer:
  frames_index: -1
  offset: 0
  # Use heading from 'gps' or 'manual'
  use_heading_from: 'gps'
  # Set manual heading in degrees if above parameter is 'manual'
  manual_heading: 5

MapGenerator:
  colored_map: True
  # Ground map parameters
  ground_map: True
  distance_threshold: 0.1
  ransac_n: 10
  num_iters: 1000
