Topics:
  gps_topic: '/gnss'
  lidar_topic: '/rslidar_points'

Extractor:
  # Mention file format to save lidar frames (for now do not set pcd)
  save_as: 'ply'

Preprocessor:
  # Specify drive distance threshold in meters, if drive distance crosses
  # this threshold it will auto trigger advanced preprocessing if set False
  drive_distance_thresh: 230
  basic_preprocessing: True
  advanced_preprocessing: False
  # Basic preprocessing parameters
  road_value_z: -2.9
  # Advanced preprocessing parameters
  k_nbs: 10
  z_thresh: 3
  z_filter: [-2.9, 3]

LidarOdometry:
  max_range: 100
  deskew: True

TrajectoryTransformer:
  frames_index: -1
  offset: 0
  # Use heading from 'gps' or 'manual'
  use_heading_from: 'gps'
  # Set manual heading in degrees if above parameter is 'manual'
  manual_heading: 5
  manual_translate: True
  latlon_offset: [52.478416, 13.337876]

MapGenerator:
  colored_map: True
  # Ground map parameters
  ground_map: True
  # Radial filter
  apply_radial_filter: True
  radial_threshold: 25 # in meters
  # Plane Segmentation filter
  distance_threshold: 0.1
  ransac_n: 10
  num_iters: 1000

LaneMarker:
  plot_histogram: True
  # Intensity Filter parameters
  num_std_devs: 5
  use_manual_param: False
  intensity_filter: [10, 40]
  # DBSCAN Clustering parameters
  eps: 0.5 # in meters
  num_points: 20
  print_progress: False
  # Alpha shapes/ Hull parameters
  # Greater alpha value -> Tight boundary
  # Lower alpha value -> Loose Boundary
  alpha: 5
