bag_file: '/home/ty/Downloads/AAI/Bags/hamburg.bag'
output_dir: '/home/ty/Downloads/AAI/Lane_Marking_Execution/hamburg'

run_dataExtractor: False
run_preprocessor: False
run_kissICP: False
run_trajectoryTransformer: True